# Generated by Django 2.2.6 on 2019-10-06 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=5000000)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('closedat', models.DateTimeField(blank=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('reftopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topics')),
            ],
        ),
    ]
